### ISSUE TITLE
PdfView.builder zoom full width

### ISSUE THREAD

**Issue by pmagnuson** [rbcprolabs/packages.flutter#62] opened 2020-05-10 16:21 UTC
I would like to have pages render at full screen width when loaded. 

1) is there a standard way to achieve this?

2) I believe I can use the `Custom Page Builder` referenced in the documentation.  
However, `PdfView.builder` does not seem to be a standard type for this class.  
Is there a more complete example showing how to use `PdfView.builder`?

Thank you,
Great Package!

**Comment by SergeShkurko** [comment] 2020-05-10 16:43
what version of the library? In recent versions, everything should be fixed

**Comment by pmagnuson** [comment] 2020-05-10 18:31
It looks like version 3.1.0 is used.  
When editing with VSCODE `PdfView.builder` results in 
```
The method 'builder' isn't defined for the type 'PdfView'.
```

**Comment by SergeShkurko** [comment] 2020-05-26 03:30
builder constructor removed, available in default constructor

**Comment by SergeShkurko** [comment] 2020-05-26 03:33
Duplicate of #68

**Comment by SergeShkurko** [comment] 2020-05-26 03:33
@pmagnuson https://github.com/rbcprolabs/packages.flutter/issues/68#issuecomment-631619222

**Closed by SergeShkurko** 2020-05-26 03:33 UTC
Labels: bug
