### ISSUE TITLE
[Flutter Web] [PDF Viewer] Can't load pdf from url

### ISSUE THREAD

**Issue by CodingDavid8** [rbcprolabs/packages.flutter#97] opened 2020-07-02 09:05 UTC
Is there any way to display a pdf by passing the url to the PdfController on Flutter Web?
I've made various attempts. 
- openAssets doesn't work since he keeps adding a 'assets/' in front of every url, otherwise it might even work... 
- openFile isn't available on flutter web
- I didn't find any documentation on how to download a pdf so I got it as UInt8List in order to pass it to the openData function.

Any advice on this?

**Comment by SergeShkurko** [comment] 2020-07-26 21:35
Duplicate of #88

**Comment by SergeShkurko** [comment] 2020-07-26 21:35
see https://github.com/rbcprolabs/packages.flutter/issues/88#issuecomment-642652489

**Closed by SergeShkurko** 2020-07-26 21:35 UTC
Labels: bug
