### ISSUE TITLE
highlight text on epub_view and getting chapters 

### ISSUE THREAD

**Issue by armanhadifatah** [rbcprolabs/packages.flutter#33] opened 2020-02-28 07:22 UTC
Hello dear 
Thank you very much for your great work on this project.

i would like to know if you have plan to add text highlight as you know it is necessary for ebook reader.

Also it is necessary to get chapters for example to show it on a drawer for chapter navigations

**Comment by proteye** [comment] 2020-04-14 15:25
@armanhadifatah Hello! Table of contents and chapter navigation are already added to the library.

**Comment by SergeShkurko** [comment] 2020-04-28 06:34
Duplicate of #48

**Closed by SergeShkurko** 2020-04-28 06:34 UTC
Labels: enhancement

**Comment by SergeShkurko** [comment] 2020-04-28 17:07
https://github.com/rbcprolabs/packages.flutter/issues/48#issuecomment-620736734

**Comment by mrifni** [comment] 2020-07-08 15:06
would text highlight be added anytime soon ?
