### ISSUE TITLE
open files for web version

### ISSUE THREAD

**Issue by copypasteearth** [rbcprolabs/packages.flutter#103] opened 2020-07-29 16:00 UTC
Im getting an unsupported platform exception when trying to load a file with filepickercross plugin and load a document into the web version of pdf view. Maybe I'm doing it wrong or maybe its not supported. I don't want to load asset I just want to load file.
Error: PlatformException(Unimplemented, null, The plugin for web doesn't implement the method 'open.document.file')
thank you for your time

**Comment by SergeShkurko** [comment] 2020-07-30 22:18
Duplicate of #88

**Comment by SergeShkurko** [comment] 2020-07-30 22:18
See https://github.com/rbcprolabs/packages.flutter/issues/88#issuecomment-642652489

**Closed by SergeShkurko** 2020-07-30 22:18 UTC
Labels: enhancement
