### ISSUE TITLE
[native_pdf_view] URL / Links are not working / not clickable

### ISSUE THREAD

**Issue by nilsreichardt** [rbcprolabs/packages.flutter#148] opened 2021-01-18 17:09 UTC
**Describe the bug**
I use `native_pdf_view` for my app. Users can't click on a link / url in the pdf...

**To Reproduce**
1. Open a pdf file with some links
2. Try to open this link (click on the link)

**Expected behavior**
Link should open.

**Screenshots**
...

**Smartphone (please complete the following information):**
Tested it on Android & Web.

**Additional context**

**Comment by graknol** [comment] 2021-01-25 12:00
It can't, it only renders the PDF to an image.

Alas there's no built in support for parsing PDF annotations, thus you need to use something like [PdfPig](https://github.com/UglyToad/PdfPig) or [pdf.js](https://github.com/mozilla/pdf.js) for extracting them and passing them to your application through an API of some kind, then render those on top of the image widget in Flutter.

**Comment by SergeShkurko** [comment] 2021-03-05 11:23
Duplicate of #82

**Closed** 2021-03-05 11:23 UTC
Labels: bug
