### ISSUE TITLE
initialPage Not working

### ISSUE THREAD

**Issue by MisterB2B** [rbcprolabs/packages.flutter#157] opened 2021-02-06 17:16 UTC
NATIVE_PDF_VIEW

I've set initialPage to 3, and once the PDF is loaded, it show me the first page...

_pdfController = PdfController(
      initialPage: 3,
      document: PdfDocument.openFile(widget.link),
    );

**Comment by vsutedjo** [comment] 2021-02-14 21:27
I have the same issue, tested on Android phones.

**Comment by rakib205** [comment] 2021-02-21 17:47
same issue.

**Comment by SergeShkurko** [comment] 2021-02-26 13:05
Duplicate of #119

**Closed by SergeShkurko** 2021-02-26 13:05 UTC
Labels: bug
