### ISSUE TITLE
Application crashes when wrong document is set in assets

### ISSUE THREAD

**Issue by boskokg** [rbcprolabs/packages.flutter#56] opened 2020-04-29 22:03 UTC
So I made a mistake in writing the file name from the assets and application crashes.

Plugin should probably handle this. I am not sure if the same happens when calling openFile with wrong filePath, but for sure it crashes when using openAsset.

CrashLog:

E/AndroidRuntime(30053): FATAL EXCEPTION: Thread-6
E/AndroidRuntime(30053): Process: org.eldrider, PID: 30053
E/AndroidRuntime(30053): java.io.FileNotFoundException: flutter_assets/assets/pdfs/ELD_Rider_Instructions222.pdf
E/AndroidRuntime(30053): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
E/AndroidRuntime(30053): 	at android.content.res.AssetManager.open(AssetManager.java:824)
E/AndroidRuntime(30053): 	at android.content.res.AssetManager.open(AssetManager.java:801)
E/AndroidRuntime(30053): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.openAssetDocument(NativePDFRendererPlugin.kt:178)
E/AndroidRuntime(30053): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.access$openAssetDocument(NativePDFRendererPlugin.kt:30)
E/AndroidRuntime(30053): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openDocumentAssetHandler$1.run(NativePDFRendererPlugin.kt:86)
E/AndroidRuntime(30053): 	at java.lang.Thread.run(Thread.java:919)
I/Process (30053): Sending signal. PID: 30053 SIG: 9

**Comment by SergeShkurko** [comment] 2020-04-29 22:37
Duplicate of #50

**Closed by SergeShkurko** 2020-04-29 22:37 UTC
Labels: bug
