### ISSUE TITLE
[native_pdf_view] App crash when change page pdf

### ISSUE THREAD

**Issue by RenanDelfanti** [rbcprolabs/packages.flutter#31] opened 2020-02-22 15:13 UTC
This error occurs if I scroll the page quickly when I finish or before rendering.

D/PDF_RENDER(26338): OpenFileDocument. File: /data/user/0/br.com.bmtcloud.jasaudeanimal/cache/1122734catofos_lamina_mobile.pdf
E/MethodChannel#io.scer.pdf.renderer(26338): Failed to handle method call
E/MethodChannel#io.scer.pdf.renderer(26338): java.lang.IllegalStateException: Current page not closed
E/MethodChannel#io.scer.pdf.renderer(26338): 	at android.graphics.pdf.PdfRenderer.throwIfPageOpened(PdfRenderer.java:269)
E/MethodChannel#io.scer.pdf.renderer(26338): 	at android.graphics.pdf.PdfRenderer.close(PdfRenderer.java:184)
E/MethodChannel#io.scer.pdf.renderer(26338): 	at io.scer.pdf.renderer.document.Document.close(Document.kt:23)
E/MethodChannel#io.scer.pdf.renderer(26338): 	at io.scer.pdf.renderer.resources.DocumentRepository.close(DocumentRepository.kt:25)

Other stack

D/PDF_RENDER(28542): OpenFileDocument. File: /data/user/0/br.com.bmtcloud.jasaudeanimal/cache/1122734catofos_lamina_mobile.pdf
I/flutter (28542): aqui
E/AndroidRuntime(28542): FATAL EXCEPTION: Thread-35
E/AndroidRuntime(28542): Process: br.com.bmtcloud.jasaudeanimal, PID: 28542
E/AndroidRuntime(28542): java.lang.IllegalStateException: Current page not closed
E/AndroidRuntime(28542): 	at android.graphics.pdf.PdfRenderer.throwIfPageOpened(PdfRenderer.java:269)
E/AndroidRuntime(28542): 	at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:224)
E/AndroidRuntime(28542): 	at io.scer.pdf.renderer.document.Document.openPage(Document.kt:30)
E/AndroidRuntime(28542): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openPageHandler$1.run(NativePDFRendererPlugin.kt:129)

**Comment by SergeShkurko** [comment] 2020-02-24 15:53
Duplicate of #14

**Closed by SergeShkurko** 2020-02-24 15:53 UTC
Labels: bug
