### ISSUE TITLE
Unable to compile my app after including this package. 

### ISSUE THREAD

**Issue by real1900** [rbcprolabs/packages.flutter#117] opened 2020-08-30 17:47 UTC
Getting this error when I try to run it

Syncing files to device Web Server...
lib/ui/books/epub/epub_main_screen.dart:26:3: Error: Type 'EpubController' not found.
  EpubController _epubReaderController;
  ^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
lib/ui/books/epub/epub_main_screen.dart:26:3: Error: 'EpubController' isn't a type.
  EpubController _epubReaderController;
  ^^^^^^^^^^^^^^
lib/ui/books/epub/epub_main_screen.dart:31:29: Error: The method 'EpubController' isn't defined for the class '_EpubMainScreenState'.
 - '_EpubMainScreenState' is from 'package:submission_flutter/ui/books/epub/epub_main_screen.dart' ('lib/ui/books/epub/epub_main_screen.dart').
Try correcting the name to the name of an existing method, or defining a method named 'EpubController'.
    _epubReaderController = EpubController(
                            ^^^^^^^^^^^^^^
lib/ui/books/epub/epub_main_screen.dart:124:13: Error: The method 'EpubView' isn't defined for the class '_EpubMainScreenState'.
 - '_EpubMainScreenState' is from 'package:submission_flutter/ui/books/epub/epub_main_screen.dart' ('lib/ui/books/epub/epub_main_screen.dart').
Try correcting the name to the name of an existing method, or defining a method named 'EpubView'.
      body: EpubView(
            ^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

**Comment by SergeShkurko** [comment] 2020-09-06 11:57
Duplicate of #116

**Closed by SergeShkurko** 2020-09-06 11:57 UTC
Labels: bug
