### ISSUE TITLE
No correct scrolling for one page possible

### ISSUE THREAD

**Issue by AndroidNils** [rbcprolabs/packages.flutter#39] opened 2020-03-17 11:42 UTC
**Describe the bug**
If you have an one page pdf and you are scrolling to the top / down, the pdf is cut off, so you can't see the rest of the pdf

**To Reproduce**
1. Take a one page pdf
2. Open the PDF View
3. Smartphone in landscape
4. Scrolle up and down to see the bug

**Expected behavior**
See the entire pdf.

**Screenshots**
![IMG_1248](https://user-images.githubusercontent.com/24459435/76852091-ecec5000-684a-11ea-9e10-303ec5b010a4.PNG)
![IMG_A683CCD72665-1](https://user-images.githubusercontent.com/24459435/76852312-4b193300-684b-11ea-9ce8-04d4e6a439d5.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPad 2018

**Additional context**
-

**Comment by SergeShkurko** [comment] 2020-04-29 09:44
Duplicate of #54

**Closed by SergeShkurko** 2020-04-29 09:44 UTC
Labels: bug

**Comment by SergeShkurko** [comment] 2020-04-29 16:22
fixed in [3.0.0](https://pub.dev/packages/native_pdf_view/versions/3.0.0)
